# Pytorch Zero to GAN  : Basic tensors

### Pytorch is an open sourced deep learning library for python, it is developed by Facebook research lab. This notebook covers the exploration of few pytroch tensor functions

**Choosen pytorch tensor functions**

In [66]:
# Import torch and other required modules
import torch
import numpy as np

**Choosen torch functions**

- torch.tensor()
- torch.randn()
- torch.arange()
- torch.flatten()
- Matrix multiplications - torch.mm()  torch.mv()
- torch.argmax()
- torch.Tensor.item()

## Function 1 - torch.tensor

This function converts input data to a tensor and the input data can be a list, tuple, NumPy array, scalar, and other types.

In [40]:
#Example 1 - working
tensor_1 = torch.tensor([1,2,3,4])
tensor_1

tensor([1, 2, 3, 4])

In [41]:
print("Dimension of tensor : ",tensor_1.dim())
print("Shape of the tensor : ",tensor_1.shape)

Dimension of tensor :  1
Shape of the tensor :  torch.Size([4])


In [42]:
#Example 2 - working
tensor_2 = torch.tensor([[1,2,3],[7,8,10],[11,20,30]], dtype = torch.float32)
print(tensor_2)

print("Dimension of tensor : ",tensor_2.dim())
print("Shape of the tensor : ",tensor_2.shape)

tensor([[ 1.,  2.,  3.],
        [ 7.,  8., 10.],
        [11., 20., 30.]])
Dimension of tensor :  2
Shape of the tensor :  torch.Size([3, 3])


In [68]:
array_1 = np.random.rand(3,4) # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
tensor_3 = torch.tensor(array_1)
tensor_3

tensor([[0.2318, 0.5277, 0.6144, 0.6827],
        [0.9638, 0.2528, 0.4053, 0.6631],
        [0.5664, 0.9674, 0.6135, 0.6782]], dtype=torch.float64)

## Function 2 - torch.randn

`torch.randn` returns a tensor with randomly filled elements from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 & standard deviation 1 and the shape of the tensor determined by the `size` argument

In [43]:
#Example 1 - working
tensor_rand = torch.randn((6))
tensor_rand

tensor([-0.8254, -0.2660, -0.7612,  0.7048, -1.8596, -1.2513])

In [44]:
#Example 2 - working
tensor_rand1 = torch.randn((4,5))
tensor_rand1

tensor([[-0.7198,  0.2343, -1.1689, -1.9184, -0.8556],
        [ 0.5851,  0.9229, -0.2094,  0.0444,  0.3789],
        [-1.7424,  0.0966, -0.3040, -2.2399,  0.1730],
        [ 0.9268, -1.5848,  0.3625,  0.8362, -0.4173]])

The above examples returns the tensors & their shapes are matched with `size` argument 6 and all the elements are randomly picked from standard normal distribution. Also, check [troch.rand](https://pytorch.org/docs/stable/torch.html?highlight=torch%20rand#torch.rand) function, which returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)

## Function 3 - torch.arange 

`torch.arange` function returns a 1-D tensor with sequence of evenly spaced values within the given range [start & end). 
It requires atleast one argument i.e. `end` and the deafult value of the `start` & `step` arguments are 0 & 1 respectively 

- This function is similar to [numpy.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) function

In [45]:
#Example 1 - working
torch.arange(10, dtype = torch.int64)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Returns a 1D tensor of 10 values with evenly spaced of step size 1 and all are integers. This function consider the end point as end- stepsize and so the end point in this example would be 9 (10 -1)

In [46]:
#Example 2 - working
torch.arange(start = 2, end = 30, step= 2.5, dtype = torch.int32)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       dtype=torch.int32)

Returns a 1D tensor of evenly spaced values starting from 2 to 30. Observed that the tensor elements are rounded, since the given data type is an integer and also noticed that the space between the consecutive elements doesn't match with the given step size

In [47]:
#Example 3 - working
torch.arange(start = 2, end = 30, step= 2.5, dtype = torch.float32)

tensor([ 2.0000,  4.5000,  7.0000,  9.5000, 12.0000, 14.5000, 17.0000, 19.5000,
        22.0000, 24.5000, 27.0000, 29.5000])

In this example the data type has changed to float and now noticed that the space between the consecutive elements were exactly matches with the given step size 2.5 

In [48]:
# Example 4 - breaking (to illustrate when it breaks)
torch.arange(start = 2, end = 10, step= -1, dtype = torch.int32)

RuntimeError: invalid argument 2: upper bound and larger bound inconsistent with step sign at c:\n\pytorch_1559129895673\work\aten\src\th\generic/THTensorMoreMath.cpp:650

It is a RuntimeError, because Start & end bound signs are not consistent with step sign.

This function can be used to generate a sequence of evenly spaced elements as a 1D tensor

## Function 4 - torch.flatten()

This function helps to flattens the input(multiple dimensions) to a  dimension tensor. It is a combination of [torch.reshape](https://pytorch.org/docs/stable/torch.html?highlight=torch%20reshape#torch.reshape) & [torch.squeeze](https://pytorch.org/docs/stable/torch.html?highlight=torch%20squeeze#torch.squeeze) functions. 

It requires atleast one argument, i.e. a tensor. Start & end dimensions are optional & default values are 0 & -1 respectively

In [49]:
# Example 1 - working

input_tensor = torch.tensor([[4,5],[6,7],[8,9]])
print("Shape of the input tensor : ",input_tensor.shape)

flatten_it = torch.flatten(input_tensor)
print("Shape of the flatten tensor :",flatten_it.shape)
flatten_it

Shape of the input tensor :  torch.Size([3, 2])
Shape of the flatten tensor : torch.Size([6])


tensor([4, 5, 6, 7, 8, 9])

This example returns a input tensor of size (3,2) to a 1-D tensor of size (6), which is equal to number of elements in the input tensor

In [50]:
# Example 2 - working
input_tensor = torch.tensor([[[4,5,1],[6,7,8]],[[8,9,10],[1,1,8]]])
print("Shape of the input tensor : ",input_tensor.shape)

flatten_it1 = torch.flatten(input_tensor,start_dim = 1)
print("Shape of the flatten tensor :",flatten_it1.shape)
flatten_it1


Shape of the input tensor :  torch.Size([2, 2, 3])
Shape of the flatten tensor : torch.Size([2, 6])


tensor([[ 4,  5,  1,  6,  7,  8],
        [ 8,  9, 10,  1,  1,  8]])

First example shows that the whole input tensor flattened to a 1-D tensor, however, it is possible to flattens only specific parts of input tensor, which is shown in 2nd example.

Input tensor of size (2,2,3) flattens to a size of (2,6). 

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
input_tensor = torch.tensor([[[4,5,1],[6,7,8]],[[8,9,10],[1,1,8]]])
print("Input tensor size :", input_tensor.shape)

Input tensor size : torch.Size([2, 2, 3])


In [52]:
flatten_tensor = torch.flatten(input_tensor,start_dim = 2, end_dim = 1)
print(flatten_tensor.shape)
flatten_tensor

RuntimeError: flatten() has invalid args: start_dim cannot come after end_dim

This function also have the end_dim argument and by default it's value is '-1'.  Start_dim value should come after end_dim value

This function helps to flatten an 3D image to a 1-D tensor, which is always the case for ANN input layer. This function also helps to convert the convolutional layer to linear layer 

## Function 5 - matrix multiplications - (torch.mm/mv)
`torch.mm` - Performs a matrix multiplication of the two matrices. 

`torch.mv` - Performs a matrix-vector product of the matrix and vector

These functions does not do broadcasting



In [53]:
# Example 1 - working with torch.mm

matrix_1 = torch.randn(3,3)
matrix_2 = torch.ones(3,2)
result = torch.mm(matrix_1,matrix_2)
print(result.shape)
result

torch.Size([3, 2])


tensor([[ 0.6604,  0.6604],
        [ 2.2407,  2.2407],
        [-0.6707, -0.6707]])

This example returns a tensor of size (3,2); matrix_1 is a (3 x 3) tensor & matrix_2 is a (3 x 2) tensor and the resultant matrix multiplication is a (3 x 2) tensor

In [54]:
# Example 2 - working with torch.mv

matrix = torch.randn(3,2)
vec = torch.randn(2)
result_mv = torch.mv(matrix,vec)
print(result_mv.shape)
result_mv

torch.Size([3])


tensor([-0.7140, -1.2720, -0.4160])

This example returns a tensor of size (3); matrix_1 is a (3 x 2) tensor & vec is a 1-D tensor of size 2and the resultant matrix-vector multiplication is a 1-D tensor of size 3

In [55]:
# Example 3 - breaking (to illustrate when it breaks)

matrix_1 = torch.randn(3,3)
matrix_2 = torch.ones(2,2)
result = torch.mm(matrix_1,matrix_2)
print(result.shape)
result

RuntimeError: size mismatch, m1: [3 x 3], m2: [2 x 2] at c:\n\pytorch_1559129895673\work\aten\src\th\generic/THTensorMath.cpp:940

There is a mismatch of matrix shapes. Matrix multiplication will happen only if the no. of. columns in matrix_1 should be equal to no. of. rows in matrix_2. 

These two functions are performing matrix operations, which is essential for building a neural nets from scratch

## Function 6 - torch.argmax()

This function returns the indices of the maximum value of all elements in the input tensor

In [56]:
# Example 1 - working
t1 = torch.tensor([10,25,70,100,90])
torch.argmax(t1)

tensor(3)

This example returns the indice of the maximum value of the input tensor. Maximum value of the input tensor is 100 & it's index is 3

In [57]:
# Example 2 - working
t2 = torch.tensor([[3,5],[90,10]])
print(t2)
torch.argmax(t2,dim = 1) # If dim = None, the argmax of the flattened input is returned 

tensor([[ 3,  5],
        [90, 10]])


tensor([1, 0])

This example returns the indices of the maximum value of the input tensor along row axis and the output tensor is a 1-D tensor

In [58]:
# Example 3 - breaking (to illustrate when it breaks)
t3 = torch.randn(3,3)
print(t3)
torch.argmax(t3,dim = 2)

tensor([[ 0.5535, -0.7249,  0.8329],
        [ 0.7672, -0.6146, -3.3187],
        [-0.0641, -0.5766, -2.1040]])


RuntimeError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Input tensor is a 2-dimension and the argmax output should be a 1-D tensor or a flattened ouput.

This function would be useful for when you need to know the max. index of the classification model outputs 

## Function 7 - torch.tensor.item() 

Returns the value of this tensor as a standard Python number.

In [59]:
# Example 1 - working

t1 = torch.tensor([100])
print(t1)
t1.item()

tensor([100])


100

This example returns the tensor([100]) to 100 

In [60]:
# Example 2 - working
t2 = torch.tensor([[99]])
print(t2)
t2.item()

tensor([[99]])


99

This example returns the tensor([99]) to 99 

In [61]:
# Example 3 - breaking (to illustrate when it breaks)
t3 = torch.randn(2,2)
t3.item()

ValueError: only one element tensors can be converted to Python scalars

This function expects the tensors with one element. For other cases, see `tolist()`.

This function would be useful to use the output of single valued tensors as a variable to other functions/objects.

## Conclusion

In summary, We had covered 5 different basic to intermediate tensor functions out of many available pytorch tensor functions. To further explore tensor functions, please do visit the [Pytorch official documentation](https://pytorch.org/docs/stable/torch.html?highlight=torch%20linspace#)

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://deeplizard.com/learn/video/fCVuiW9AFzY

In [63]:
!pip install jovian --upgrade --quiet

In [64]:
import jovian

<IPython.core.display.Javascript object>

In [69]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "vineel369/pytorch-zero-to-gan-01-basic-tensor-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/vineel369/pytorch-zero-to-gan-01-basic-tensor-operations


'https://jovian.ml/vineel369/pytorch-zero-to-gan-01-basic-tensor-operations'